# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: chillfinn.github.io
email: 
description: > # this means to ignore newlines until "baseurl:"
  My github site, slightly branded
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chillfinn.com" # the base hostname & protocol for your site
twitter_username: chillfinn
github_username:  chillfinn

# Build settings
markdown: kramdown
