# Site settings
title: The Chillfinn's Github Jekyll place
email: ville@chillfinn.com
description: > # this means to ignore newlines until "baseurl:"
  Just starting out.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chillfinn.github.io" # the base hostname & protocol for your site
twitter_username: chillfinn
github_username:  chillfinn

# Build settings
markdown: kramdown
